spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///dubhe_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
